---
title: "EEG Data"
author: "Ian J. Kahrilas"
date: "9/9/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load in packages

```{r load in tidyverse}
library(tidyverse)
```

Let us first create a vector with our .mul and .evt names

```{r file names}
#vector of all files in working directory
files <- list.files()
##retain only .evt and .mul files
mul_names <- str_subset(files, ".mul")
evt_names <- str_subset(files, ".evt")
```
Read in .mul and .evt files
```{r read in .evt files, warning = FALSE, message = FALSE}
#preallocate space
mul_files <- vector("list", length(mul_names))
evt_files <- vector("list", length(evt_names))

##read in evt files, make columns for block, number of trials, and pid. This cleans names up, too.
for (i in seq_along(evt_names)) {
  evt_files[[i]] <- read_table(evt_names[i])
  evt_files[[i]] <- separate(evt_files[[i]], `Code	TriNo	Comnt`, into = c("block", "n_trials"), sep = " ")
  evt_files[[i]]$block <- gsub("\t42\t200000\t", "", evt_files[[i]]$block)
  evt_files[[i]]$block <- gsub(":", "", evt_files[[i]]$block)
  evt_files[[i]]$n_trials <- gsub(" avs", "", evt_files[[i]]$n_trials)
  evt_files[[i]] <- evt_files[[i]] %>% 
    mutate(pid = as.numeric(str_extract(evt_names[i], "[0-9]{7,}"))) %>%
    select(-Tmu)
} 

# reduce the list into a dataframe, or tibble
evt_tbl <- reduce(evt_files, bind_rows)
```
 
Read in .mul files

```{r read in .mul files, message = FALSE, warning = FALSE}
#define variable that has number of blocks, which is 7
n_block <- nrow(evt_files[[1]])
# make vector of blocks in correct order to use in the mul files
block_order <- str_remove(evt_files[[1]]$block, "42\t200000\t")
# this read all .mul files into a list and generates pid, block, and ms variables
mul_files <- map(mul_names, ~ {
  read_table2(.x, skip = 1) %>%
  mutate(
    pid = as.numeric(str_extract(.x, "[0-9]{7,}")),
    block = rep(block_order, each = nrow(.) / 7),
    ms = rep(seq(from = -200, to = 3000, 
                   by = ((3200 + (3200 / (nrow(.)/7))) / (nrow(.)/7))),
               times = 7)
    )
  }
  )

mul_tbl <- reduce(mul_files, full_join)
```

```{r check em out}
glimpse(evt_tbl)
glimpse(mul_tbl)
```

```{r clean up variable/condition names}
# clean up block names
evt_tbl$block <- str_remove(evt_tbl$block, "42\t200000\t")

evt_tbl$block <- map_chr(evt_tbl$block, ~ {
  str_replace_all(.x, "Positive", "Pos") %>%
  str_replace_all(., "Negative", "Neg") %>%
  str_replace_all(., "Neutral", "Neu") %>%
  str_replace_all(., "Increase", "Inc") %>%
  str_replace_all(., "Decrease", "Dec")
  }
  )

# clean up electrode names in mul_tbl
names(mul_tbl) <- gsub("_.*", "", names(mul_tbl))
```

```{r merge mul and evt dataframes}
erp <- full_join(mul_tbl, evt_tbl, by = c("pid", "block"))
# can also drop x72 and x73 columns, as they don't contain anything!
erp <- erp %>% select(-c(X74, X73, X72))
# fix incorrect pid
erp$pid[erp$pid == 201206832] <- 206201832
write_csv(erp, "erp_data.csv")
```

Now, we are set to do some analyses!