---
title: "Exploratory Data Analysis with Pawpaw Miller"
author: "Ian Kahrilas"
date: "1/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
# load in dataset
per_erp <- read_csv("per_erp.csv")
library(pander)
```

# Univariate Analyses

## Variables
The following variables are a part of the dataset used for PER

```{r variables for PER}
matrix(names(per_erp), ncol = 2)
```

```{r descriptive stats on variables of interest}
per_erp %>% 
  summarize("PA Mean" = mean(pos_affectivity, na.rm = TRUE),
            "PA SD" = sd(pos_affectivity, na.rm = TRUE),
            "NA Mean" = mean(neg_affectivity, na.rm = TRUE),
            "NA SD" = sd(neg_affectivity, na.rm = TRUE),
            "StM Mean" = mean(savoring_moment, na.rm = TRUE),
            "StM SD" = sd(savoring_moment, na.rm = TRUE),
            "Anticipating Mean" = mean(anticipating, na.rm = TRUE),
            "Anticipating SD" = sd(anticipating, na.rm = TRUE),
            "Reminiscing Mean" = mean(reminiscing, na.rm = TRUE),
            "Reminiscing SD" = sd(reminiscing, na.rm = TRUE)) %>% 
  pander()


```


## PANAS

Visualized the distribution and QQ plot of PANAS

```{r}
per_erp %>% 
  group_by(pid) %>% 
  summarize(PA = mean(pos_affectivity, na.rm = TRUE)) %>% 
  ggplot(., (aes(PA))) +
    geom_histogram(bins = 31)
```


## Slide with Bullets

- Bullet 1
- Bullet 2
- Bullet 3

## Slide with R Output

```{r cars, echo = TRUE}
summary(cars)
```

## Slide with Plot

```{r pressure}
plot(pressure)
```

