---
title: "EEG Data"
author: "Ian J. Kahrilas"
date: "9/9/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load in packages

```{r load in tidyverse}
library(tidyverse)
library(here)
```

Let us first create a vector with our .mul and .evt names

```{r file names}
# vector of all files in working directory partitioned by avg montage and evt files
files_mast <- list.files(here("data", "mastoid_ref"))
files_avg <- list.files(here("data", "avg_ref"))
files_evt <- list.files(here("data", "evt"))
```
Read in .mul and .evt files
```{r read in .evt files, warning = FALSE, message = FALSE}
#preallocate space
mastoid <- as_tibble(matrix(data = NA_real_, nrow = 580454, ncol = 80))
avg <- as_tibble(matrix(data = NA_real_, nrow = 580454, ncol = 80))
evt <- tibble(
  Tmu = rep(NA, times = 51*7),
  block = rep(NA, times = 51*7),
  n_trials = rep(NA, times = 51*7),
  pid = rep(NA, times = 51*7),
  prop_trials = rep(NA, times = 51*7)
)

# make list of block names
block_names <- c("Pos_Inc",
                 "Pos_Dec",
                 "Pos_Watch",
                 "Neg_Inc",
                 "Neg_Dec",
                 "Neg_Watch",
                 "Neu_Watch")

##read in evt files, make columns for block, number of trials, and pid. This cleans names up, too.
evt <- map_df(files_evt, ~{
  read_table(here("data", "evt", .x)) %>% 
  separate(`Code	TriNo	Comnt`, into = c("block", "n_trials"), sep = " ") %>% 
  mutate(block = str_extract(block, block_names),
         n_trials = as.numeric(str_extract(n_trials, "[0-9]{2}")),
         pid = str_extract(.x, "[0-9]+"),
         prop_trials = n_trials / 40)
})
```
 
Read in eeg files

```{r read in .mul files, message = FALSE, warning = FALSE}
# this reads all mastoid-referenced files into a list and generates pid, block, and ms variables
mastoid <- map_df(here("data", "mastoid_ref", files_mast), ~ {
  read_table2(.x, skip = 1) %>%
  mutate(
    pid = as.numeric(str_extract(.x, "[0-9]{7,}")),
    block = rep(block_names, each = nrow(.) / 7),
    ms = rep(seq(from = -200, to = 3000, 
                   by = ((3200 + (3200 / (nrow(.)/7))) / (nrow(.)/7))),
               times = 7)
    )
  }
  )
# this reads all average-referenced files into a list and generates, pid, block, and ms variables
avg <- map_df(here("data", "avg_ref", files_avg), ~ {
  read_table2(.x, skip = 1) %>%
  mutate(
    pid = as.numeric(str_extract(.x, "[0-9]{7,}")),
    block = rep(block_names, each = nrow(.) / 7),
    ms = rep(seq(from = -200, to = 3000, 
                   by = ((3200 + (3200 / (nrow(.)/7))) / (nrow(.)/7))),
               times = 7)
    )
}
  browser()
  )
```

```{r check em out}
glimpse(evt_tbl)
glimpse(mul_tbl)
```

```{r clean up variable/condition names}
# clean up block names
evt_tbl$block <- str_remove(evt_tbl$block, "42\t200000\t")

evt_tbl$block <- map_chr(evt_tbl$block, ~ {
  str_replace_all(.x, "Positive", "Pos") %>%
  str_replace_all(., "Negative", "Neg") %>%
  str_replace_all(., "Neutral", "Neu") %>%
  str_replace_all(., "Increase", "Inc") %>%
  str_replace_all(., "Decrease", "Dec")
  }
  )

# clean up electrode names in mul_tbl
names(mul_tbl) <- gsub("_.*", "", names(mul_tbl))
```

```{r merge mul and evt dataframes}
erp <- full_join(mul_tbl, evt_tbl, by = c("pid", "block"))
# can also drop x72 and x73 columns, as they don't contain anything!
erp <- erp %>% select(-c(X74, X73, X72))
# fix incorrect pid
erp$pid[erp$pid == 201206832] <- 206201832
write_csv(erp, "erp_data.csv")
```

Now, we are set to do some analyses!